name: "Deploy to Elastic Beanstalk"
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_PLATFORM: arn:aws:elasticbeanstalk:us-east-1::platform/Ruby 3.0 running on 64bit Amazon Linux 2/3.4.10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.0
      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -i ${{ secrets.AWS_APP_NAME }} -p "${{ env.AWS_PLATFORM }}" -k ${{ secrets.AWS_KEY_NAME }} --region ${{ secrets.AWS_REGION }}
          eb deploy ${{ secrets.AWS_ENVIRONMENT_NAME }}
