name: "Deploy to Elastic Beanstalk"
on: workflow_dispatch
# on:
#  push:
#    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Elastic Beanstalk
    steps:
    - uses: actions/checkout@v3
      name: Checkout code on runner
    - uses: hmanzur/actions-aws-eb@v1.0.0
      name: Deploy with EB CLI
      with:
        command: 'deploy ${{ secrets.ENVIRONMENT_NAME }}'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
