name: "Deploy to Elastic Beanstalk"
on: workflow_dispatch
# on:
#  push:
#    branches: [ "main" ]
jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_PLATFORM: ruby-3.0
      APP_NAME: rails-app
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.10.0
    - name: Install EB CLI using pip
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -i ${{env.APP_NAME}} -p ${{env.AWS_PLATFORM}} -k ${{secrets.AWS_KEY_NAME}} --region ${{secrets.AWS_DEFAULT_REGION}}
        eb deploy ${{ env.APP_NAME }}
